spring:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs